name: create new branch and pr

on: workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          
      - name: evaluate branch name
        run: echo "BRANCH_NAME=release-web-$(date --iso-8601)" >> $GITHUB_ENV

      - name: Create new release branch
        run: git push origin "development:$BRANCH_NAME"
        
      - name: create-pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "$BRANCH_NAME"                               
          destination_branch: "main"                     
          pr_title: "Pulling $BRANCH_NAME into main" 
          pr_body: |                                        # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*
  
              _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}      # If blank, default: secrets.GITHUB_TOKEN
