name: create new branch and pr

on: workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          
      - name: evaluate branch name
        id: branchname
        run: echo "branch-name=release-web-$(date --iso-8601)" >> $GITHUB_OUTPUT

      - run: echo ${{ steps.branchname.outputs.branch-name }}
      - name: Create new release branch
        run: git push origin "development:${{ steps.branchname.outputs.branch-name }}"
        
      - name: create-pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ steps.branchname.outputs.branch-name }}"                               
          destination_branch: "main"                     
          pr_title: "Pulling ${{ steps.branchname.outputs.branch-name }} into main" 
          pr_body: |                                        # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*
  
              _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}      # If blank, default: secrets.GITHUB_TOKEN
