name: Create release branch
concurrency:
  group: create-release
  cancel-in-progress: false
on: workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: development
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Create new release branch
        run: |
          PULL_REQUEST_BRANCH=release-web-$(date --iso-8601)
          git push origin "development:${PULL_REQUEST_BRANCH}"
          echo "PULL_REQUEST_BRANCH=${PULL_REQUEST_BRANCH}" >> $GITHUB_ENV

      - name: Configure pull request details
        run: |
          PULL_REQUEST_TITLE="Release web $(date '+%Y %m %d')"
          PULL_REQUEST_LOGS=$(git log --cherry-pick --oneline origin/main...origin/development)
          echo "PULL_REQUEST_TITLE=${PULL_REQUEST_TITLE}" >> $GITHUB_ENV
          echo "PULL_REQUEST_LOGS=${PULL_REQUEST_LOGS}" >> $GITHUB_ENV

      - name: Create pull request
        id: create-pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          source_branch: ${{ env.PULL_REQUEST_BRANCH }}
          # pr_reviewer: "archana-shetty"
          pr_title: ${{ env.PULL_REQUEST_TITLE }}
          pr_body: |
            ## Description
            ### What changes were made?
            ${{ env.PULL_REQUEST_LOGS }}
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Pull request url
        run: echo ${{steps.create-pull-request.outputs.pr_url}}
