name: create new branch and pr

on: workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Create new release branch
        run: git push origin "development:release-web-$(date --iso-8601)"
        
      - name: create-pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "release-web-2023-01-24"                               
          destination_branch: "main"                     
          pr_title: "Pulling release-web-$(date --iso-8601) into master" 
          pr_body: |                                        # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*
  
              _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}      # If blank, default: secrets.GITHUB_TOKEN
