
name: trigger tests in another repository and wait for result
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - edited  
jobs:
  trigger-test-and-wait:
    runs-on: ubuntu-latest
    if: "!contains( github.head_ref, 'release-web')"
    steps:
      - run: echo "${{ github.head_ref }}"
