name: trigger tests in another repository and wait for result
on: workflow_dispatch
jobs:
  trigger-test-and-wait:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the automated test in another repo and wait for the result
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: amuthansakthivel
          repo: SeleniumAppiumTestsInGithubRunners
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_file_name: repository-dispatch.yml
          ref: master
          client_payload: '{"github": ${{ toJson(github) }}}'
