name: trigger tests in another repository and wait for result
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  trigger-test-and-wait:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the automated test in another repo and wait for the result
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: amuthansakthivel
          repo: SeleniumAppiumTestsInGithubRunners
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_file_name: 3-web-test.yml
          ref: master
          propagate_failure: true
          client_payload: '{"client_payload": "test", "TEST_ENV": "DEVELOP"}'
